import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/navbar";
import Footer from "@/components/ui/footer";
import { AuthProvider } from "@/context/AuthContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
    <html className="flex justify-center w-full h-full" lang="en">
      <body className={`${inter.className} flex justify-center h- full w-full`}>
        <div className="">
         <Navbar />
         <main className="flex-grow w-full">
          {children}
        </main>
        <Footer />
        </div>
      </body>
    </html>
    </AuthProvider>
  );
}
